### ISSUE TITLE
Compiling wass in ubuntu 14.04

### ISSUE THREAD

**Issue by pvguima** [fbergama/wass#1]
I am still using ubuntu 14.04 version, despite it is not supporter by this version probably other users can be interesting on it. 

Some repositories are missing or using a old version like ffmpeg, cmake and boost

For ffmpeg could be interesting to add it in your ppa
add-apt-repository ppa:samrog131/ppa
apt-get install ffmpeg-set-alternatives
The PPA also contains other packages that you may not want. Remove the ppa after installation.
add-apt-repository --remove ppa:samrog131/ppa

For upgrade the cmake version:
http://askubuntu.com/questions/610291/how-to-install-cmake-3-2-on-ubuntu-14-04

To install the wass system it also asking me a versions of Boost 1.58 or higher, so I removed the old libboost-all-dev and installed the version 1.58 from boost.org:
http://www.boost.org/users/history/version_1_58_0.html

First I tried the newest boost version (1.62) and it didn't work, so maybe is better use the version 1.58. 

I hope it helps. 

Pedro

**Comment by fbergama** [comment]
Hi,
thank you for the report and the useful summary on how to install boost and cmake in Ubuntu 14.04.

I think that the problem you mentioned was related to the cmake build system and I've created a fix for that in the temporary "issue1_fix" branch.

Can you please do a

```
git fetch
git checkout issue1_fix
```

and try again with the whole cmake / make / make install stuff? (please delete the whole build subduer before). If everything is working properly I'll merge it into the master branch.

Thank you,
Filippo

**Comment by pvguima** [comment]
Thank you Filippo, 

Problem solved. I did that but I still with problems with boost and pthread, so I just remove the boost version 1.61 and install the version 1.58 (same as in ubuntu 16.04). 

Now the installation is working in 14.04, I will recommend that in the last post.

**Comment by fbergama** [comment]
I'm glad that the problem is solved. I'm looking forward to hear your impressions about the software.

It's strange that with boost 1.61 is not working.. what's exactly your problem? I've tested exactly that version on a virtual machine without issues.

**Comment by pvguima** [comment]
Hi Filippo,

I don't remember exactly what was print in the scream, but was something
about the boost and pthread, so this is why I tried to reinstall the boost.

After that I recompiled removed the build directories and recompile
everything. So now it is working.

But I was a bit frustrated after that, because my matlab don't have the
pcread the test crashs in the end.
I will have to check my licence and see if I can upgrade my matlab version.
If it is not possible, I will try to find a time to create some python
script to convert .ply files in .mat.

I couldn't explore too much the pipeline, we just comeback from a boat
experiment and I have many buoys data to analyse first. But will try to do
it just after that.

Thanks a lot,

Pedro

2016-10-08 15:41 GMT+02:00 Filippo Bergamasco <notifications@github.com>:

**Comment by maccensi** [comment]
Hi Filippo,

I also have the same problem compiling wass. I've followed the step by step installation with Pedro comments and also using your repos issue1_fix. Here is the full error message during the make : 
[ 15%] Building CXX object wass_prepare/CMakeFiles/wass_prepare.dir/wass_prepare.cpp.o
Linking CXX executable wass_prepare
/usr/bin/ld: CMakeFiles/wass_prepare.dir/wass_prepare.cpp.o: référence au symbole non défini «pthread_rwlock_wrlock@@GLIBC_2.2.5»
//lib/x86_64-linux-gnu/libpthread.so.0: error adding symbols: DSO missing from command line
collect2: error: ld returned 1 exit status
make[2]: *** [wass_prepare/wass_prepare] Erreur 1
make[1]: *** [wass_prepare/CMakeFiles/wass_prepare.dir/all] Erreur 2
make: *** [all] Erreur 2

It seems the -lpthread is not added in the lib flags or not placed at the end of the list...

Thanks for your help,

Mickael

**Comment by fbergama** [comment]
It is strange, It's working on both my Ubuntu 14.04 virtual machine an Pedro's. Anyway... you are right it's related to pthread. Can you please try to change line 22 of the file

```
<wass_dir>/src/wass_prepare/CMakeLists.txt
```

from 

```
target_link_libraries( ${PROJECT_NAME} ${OpenCV_LIBS} ${Boost_LIBRARIES}   )
```

to:

```
target_link_libraries( ${PROJECT_NAME} ${OpenCV_LIBS} ${Boost_LIBRARIES}  pthread  )
```

I'm looking forward to see if that solves the issue...
Thank you!

Filippo

**Comment by maccensi** [comment]
It worked! I also had to change this line in wass_match/CMakeLists.txt,  wass_autocalibrate/CMakeLists.txt and wass_stereo/CMakeLists.txt to successfully make the installation.

Thanks,

Mickaël

**Comment by fbergama** [comment]
Great! I'll make the changes to the main branch as soon as I can test it successfully also on other platforms.
