### ISSUE TITLE
WASS in Windows_ Redis

### ISSUE THREAD

**Issue by trkim117** [fbergama/wass#11]
Hi!
Is WASS working well in Windows?
When we tested by clicking 
launch_wassjs.bat,
we had error message that
"We can't find Redis-x64-3.2.100/redis-sever.exe"
Could you let us know how we can solve this problem?
Thank you in advance!!
Best wishes,
KIM

**Comment by fbergama** [comment]
Hi KIM,
Did you use the Windows binary version available on the website?

**Comment by trkim117** [comment]
Thank you for immediate information.
We downloaded and used
wass_1.4_win32_x64.zip Everything was OK until we click the launch_wass.bat.
It produced redis errors and did not show the windows in the test.
Were there this kind of errors before other window users?


--- Original Message ---
From : "Filippo Bergamasco"<notifications@github.com>
To : "fbergama/wass"<wass@noreply.github.com>
Cc : "trkim117"<trkim@kunsan.ac.kr>, "Author"<author@noreply.github.com>
Date : 2019/07/23 화요일 오후 10:19:54
Subject : Re: [fbergama/wass] WASS in Windows_ Redis (#11)

Hi KIM,
Did you use the Windows binary version available on the website?
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or mute the thread.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/fbergama/wass/issues/11?email_source=notifications\u0026email_token=AF6L6FVJNY56P2T367LTGZDQA4APVA5CNFSM4IGDQ7R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TCU3I#issuecomment-514206317", "url": "https://github.com/fbergama/wass/issues/11?email_source=notifications\u0026email_token=AF6L6FVJNY56P2T367LTGZDQA4APVA5CNFSM4IGDQ7R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2TCU3I#issuecomment-514206317", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by trkim117** [comment]
We tried Windows 7 and 10 both, but we had the same problems.
The redis issue seems like something to do with  linux.
I wonder I have to try again with Linux, but problem is that I am not used to Linux.
Are there many users using WASS with windows?
Thank you!!

**Comment by trkim117** [comment]
We had to unzip the Redis file manually!!

**Comment by fbergama** [comment]
Hi Kim,
sorry for the late reply. I'll mention in the website that you have to manually extract the Redis package. Thanks for spotting what the problem was :+1:

**Comment by trkim117** [comment]
Dear Filippo Bergamasco:
How are you?
Several questions and progress we made.
1) Even we extracted Redis package, it had several problems in Windows 7 but
we don't have any problems in Windows 10. So we switched to Windows 10.

2)mesh.ply is not saved as in "getting started". Where do we can make it?

3)Without OPENCV, it works fine till "getting started". Which part the "OPENCV" are needed?

4)Is there kind of Flowchart to show the procedure from two stereo images to wave height distribution.

Thank you for your time.
Best wishes,
TAERIM KIM


--- Original Message ---
From : "Filippo Bergamasco"<notifications@github.com>
To : "fbergama/wass"<wass@noreply.github.com>
Cc : "trkim117"<trkim@kunsan.ac.kr>, "State change"<state_change@noreply.github.com>
Date : 2019/07/25 목요일 오후 6:59:09
Subject : Re: [fbergama/wass] WASS in Windows_ Redis (#11)

Hi Kim,
sorry for the late reply. I'll mention in the website that you have to manually extract the Redis package. Thanks for spotting what the problem was 👍
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/fbergama/wass/issues/11?email_source=notifications\u0026email_token=AF6L6FWAFH32UZVXF66IUCDQBF2O3A5CNFSM4IGDQ7R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2Y7Z7Q#issuecomment-514981118", "url": "https://github.com/fbergama/wass/issues/11?email_source=notifications\u0026email_token=AF6L6FWAFH32UZVXF66IUCDQBF2O3A5CNFSM4IGDQ7R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD2Y7Z7Q#issuecomment-514981118", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]

**Comment by fbergama** [comment]
Hi KIM,

1) We have never tested the pipeline with Windows 7, thank you for reporting that it's not compatible

2) To save the file "mesh.ply" you need to set

SAVE_AS_PLY=true

in the stereo_config.txt file and

"savediskspace":false  

in worksession.json

3) What do you mean "without opencv"?

4) Unfortunately we do not have a simple tutorial yet to go from stereo images to the final height distribution. The general procedure is to load the point cloud in Matlab, interpolate it on a regular grid (see triscattered interpolant) and then compute what you are interested with from the grid.

Filippo

**Comment by trkim117** [comment]
Thank you for your help and information.
We successfully tested the examples provided in your web site and now
I can see how it works at some extent.
Now, we are working on hardwares to take stereo images.
In terms of OPENCV, we could finsh the test without installing  OPENCV, so
I wonder when OPENCV is utillized in PIPELINE.
Thank you for your time.


--- Original Message ---
From : "Filippo Bergamasco"<notifications@github.com>
To : "fbergama/wass"<wass@noreply.github.com>
Cc : "trkim117"<trkim@kunsan.ac.kr>, "State change"<state_change@noreply.github.com>
Date : 2019/08/07 수요일 오후 8:47:57
Subject : Re: [fbergama/wass] WASS in Windows_ Redis (#11)

Hi KIM,
We have never tested the pipeline with Windows 7, thank you for reporting that it's not compatible
To save the file "mesh.ply" you need to set
SAVE_AS_PLY=true
in the stereo_config.txt file and
"savediskspace":false
in worksession.json
What do you mean "without opencv"?
Unfortunately we do not have a simple tutorial yet to go from stereo images to the final height distribution. The general procedure is to load the point cloud in Matlab, interpolate it on a regular grid (see triscattered interpolant) and then compute what you are interested with from the grid.
Filippo
—
You are receiving this because you modified the open/close state.
Reply to this email directly, view it on GitHub, or mute the thread.
[ { "@context": "http://schema.org", "@type": "EmailMessage", "potentialAction": { "@type": "ViewAction", "target": "https://github.com/fbergama/wass/issues/11?email_source=notifications\u0026email_token=AF6L6FQMTCE53ZX2RBMTFG3QDKY63A5CNFSM4IGDQ7R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3YEDWQ#issuecomment-519061978", "url": "https://github.com/fbergama/wass/issues/11?email_source=notifications\u0026email_token=AF6L6FQMTCE53ZX2RBMTFG3QDKY63A5CNFSM4IGDQ7R2YY3PNVWWK3TUL52HS4DFVREXG43VMVBW63LNMVXHJKTDN5WW2ZLOORPWSZGOD3YEDWQ#issuecomment-519061978", "name": "View Issue" }, "description": "View this Issue on GitHub", "publisher": { "@type": "Organization", "name": "GitHub", "url": "https://github.com" } } ]
