### ISSUE TITLE
SAVE_AS_PLY=true not working?

### ISSUE THREAD

**Issue by caiostringari** [fbergama/wass#13]
Hi, 

I am trying to get the output to be written as a .ply file but the pipeline seems to ignore my request.

I am running with Docker and using the .yml in the README as example. The reconstruction runs fine and I get the .xyzC file but no .ply.

I logged into the container and verified that /DATA_CONF/stereo_config.txt had SAVE_AS_PLY=true.

Alternatively, is there an easy way to read the .xyzC in python?

Cheers,

Caio

**Comment by fbergama** [comment]
Just to check, did you removed the leading "#" before SAVE_AS_PLY?

**Comment by caiostringari** [comment]
Yes, I did.

See attached my stereo_config.txt file

Do I need to change anything else?

[stereo_config.txt](https://github.com/fbergama/wass/files/4993182/stereo_config.txt)

**Comment by fbergama** [comment]
You also need to set

"savediskspace":false

in worksession.json, otherwise the ply file is created but then deleted to save space.

**Comment by caiostringari** [comment]
That did the trick. Thanks!
