### ISSUE TITLE
Error testing pipeline

### ISSUE THREAD

**Issue by jessim921003** [fbergama/wass#7]
hello,

I have this error message when running test_pipeline:

OpenCV(3.4.1-dev) Error: Assertion failed (ssize.width > 0 && ssize.height > 0) in resize, file /home/jessica/opencv/modules/imgproc/src/resize.cpp, line 4044
terminate called after throwing an instance of 'cv::Exception'
  what():  OpenCV(3.4.1-dev) /home/jessica/opencv/modules/imgproc/src/resize.cpp:4044: error: (-215) Assertion failed: ssize.width > 0 && ssize.height > 0 in function resize

/bin/bash: line 1: 20714 Aborted                 (core dumped) /home/jessica/wass/test/../dist/bin/wass_stereo /home/jessica/wass/test/WASS_TEST/synth/config/stereo_config.txt /home/jessica/wass/test/output/000000_wd/
LD_LIBRARY_PATH="" && /home/jessica/wass/test/../dist/bin/wass_stereo /home/jessica/wass/test/WASS_TEST/synth/config/stereo_config.txt /home/jessica/wass/test/output/000000_wd/: Aborted

I appreciate your help.

**Comment by fbergama** [comment]
Can you please check if the error occurs also if you switch to the dense_stereo_flow branch?

**Comment by fbergama** [comment]
Ok I can replicate your problem when using OpenCV 3.4.1.

As a workaround, you can install the 3.4.0 and compile WASS again. Everything should work as expected. In the meanwhile, I'll investigate the issue

**Comment by fbergama** [comment]
It turned out that the problem is due to an OpenCV bug. I've already reported the bug to the OpenCV maintainers:

https://github.com/opencv/opencv/issues/11131

Also, I've updated the documentation so that version 3.4.0 is installed by default
